DROP TABLE IF EXISTS `items`;
CREATE TABLE `items` (
`object_id` int(10) unsigned NOT NULL default '0',
`owner_id` int(10) NOT NULL,
`item_id` smallint(5) unsigned NOT NULL default '0',
`count` BIGINT UNSIGNED NOT NULL default '0',
`enchant_level` smallint(5) unsigned NOT NULL default '0',
`fire_val` smallint NOT NULL default '0',
`water_val` smallint NOT NULL default '0',
`wind_val` smallint NOT NULL default '0',
`earth_val` smallint NOT NULL default '0',
`dark_val` smallint NOT NULL default '0',
`holy_val` smallint NOT NULL default '0',
`class` ENUM('CONSUMABLE','MISC','EQUIPMENT','MATHERIALS','OTHER','PIECES','RECIPIES','SPELLBOOKS') NOT NULL DEFAULT 'OTHER',
`loc` enum('CLANWH','FREIGHT','INVENTORY','PAPERDOLL','PET','PET_EQUIP','VOID','WAREHOUSE','MONSTER','MAILBOX', 'MARKET') NOT NULL,
`loc_data` int(11) default NULL,
`price_sell` BIGINT unsigned NOT NULL default '0',
`price_buy` BIGINT unsigned NOT NULL default '0',
`expire_time` BIGINT NOT NULL default '0',
`custom_type1` smallint(4) unsigned NOT NULL default '0',
`custom_type2` smallint(4) unsigned NOT NULL default '0',
`mana_left` INT(11) NOT NULL DEFAULT '0',
`flags` int(11) NOT NULL default '0',
PRIMARY KEY(`object_id`),
KEY `key_owner_id` (`owner_id`),
KEY `key_loc` (`loc`),
KEY `key_item_id` (`item_id`),
KEY `key_class` (`class`),
KEY `key_loc_data` (`loc_data`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
